### ISSUE TITLE
Implement case distinguishing function (eq())

### ISSUE THREAD

**Issue by narcoticfresh** [mrix/rql-command#1]
Hi ;-)

Some backends (like our MongoDB) search case-sensitive by default. Now, obviously some clients want to search case-_in_sensitive. We couldn't find whether the RQL `eq()` should be case sensitive (checked the standard).

Now, our problem is that we run into a possibly major performance problem if we want to implement case insensitivity on _all_ `eq()` calls from the user to our MongoDB. For case-insensitive search, we need to do a Regex expr to MongoDB which then ignores all indexes.

So is there a possibility to integrate an lowercase version of the `eq()` function to the parser, maybe `ieq()` (`i` similar as `igrep` is a pendant to `grep`)? ;-)

**Comment by hairmare** [comment]
I think `like()` search should suffice here...

**Comment by narcoticfresh** [comment]
Well yes.. so we'll make our `like()` Regexes always with `/i`? @hairmare
I read that all either unrooted (without `^` at the beginning) or `/i` marked regexes always skip all indexes and require a full scan..

**Comment by hairmare** [comment]
It will after libgraviton/php-rql-parser#39, just give us a sec here please...

**Comment by narcoticfresh** [comment]
OK, ACK

**Comment by mrix** [comment]
@narcoticfresh you can also implement own operators. See [example](https://github.com/xiag-ag/rql-parser/blob/master/examples/02-extending.php)
